const sectionSettings = {
  [1 as number]: {
    title: "Origins",
    navbarBackground: "#fde8d3",
    navbarTextColor: "#000000",
    navbarCircle: "#036977",
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarCirclePosition: 0,
    navbarControlsName: "first",
  },
  [2 as number]: {
    title: "Skills: Unmasked mastery",
    navbarBackground: "#036977",
    navbarTextColor: "#ffffff",
    navbarCircle: "#FAF0D7",
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarCirclePosition: -200,
    navbarControlsName: "second",
  },
  [3 as number]: {
    title: "Projects: Signature creations",
    navbarBackground: "#FAF0D7",
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarTextColor: "#000000",
    navbarCircle: "#672019",
    navbarCirclePosition: -100,
    navbarControlsName: "third",
  },
  [4 as number]: {
    title: "Works: Devotion of a lifetime",
    navbarBackground: "#672019",
    navbarTextColor: "#fde8d3",
    navbarCircle: "#4f96a0",
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarCirclePosition: -250,
    navbarControlsName: "forth",
  },
  [5 as number]: {
    title: "Impressions: Echo long after",
    navbarBackground: "#4f96a0",
    navbarTextColor: "#ffffff",
    navbarCircle: "#dc7070",
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarCirclePosition: -300,
    navbarControlsName: "fifth",
  },
  [6 as number]: {
    title: "Contact: Knock his door!",
    navbarBackground: "#f8a97a",
    navbarTextColor: "#000000",
    navbarCircle: "#fde8d3",
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarCirclePosition: -150,
    navbarControlsName: "sixth",
  },
  [7 as number]: {
    title: "Fin",
    navbarBackground: "#fde8d3",
    navbarTextColor: "#000000",
    navbarCircle: "#672019",
    navbarCirclePosition: 0,
    navbarBackgroundInClass: "bg-falu-red-100",
    navbarControlsName: "seventh",
  },
};

export default sectionSettings;
